SELECT
--  C.CODUL AS CUATM,
--  C.FULL_CODE,
--  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D

--  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
--  C.PRGS IN (2) AND
--  C.CODUL NOT IN ('9800000')
  -- AND  
  D.ID_MDTABLE = 6297 
  
  
  ORDER BY 
  ORDINE