SELECT
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,   
  
  VB.FULL_CODE AS NR_SECTIE,                                                         
  VB.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
--   VB.COL1||'~'||VB.ORDINE AS NR_ROW,
  VB.COL2||'~'||VB.ORDINE||'~'||VB.FULL_CODE AS NR_ROW,
  VB.ORDINE,
  '00000000000' AS DECIMAL_POS,
  VB.DENUMIRE AS NUME_ROW,
  VB.COL3    AS COL1,
  VB.COL4    AS COL2,
  VB.COL5    AS COL3,
  VB.COL6    AS COL4,
  VB.COL7    AS COL5,
  VB.COL8    AS COL6,
  VB.COL9    AS COL7,
  VB.COL10    AS COL8,
  VB.COL11   AS COL9,
  VB.COL12   AS COL10,
  VB.COL13   AS COL11
FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
  SUM(CASE WHEN D.CAPITOL IN (1010)  THEN D.COL1_S ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.CNT ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL2 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL3 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL4 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL5 ELSE NULL END) AS COL7,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL6 ELSE NULL END) AS COL8,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL7 ELSE NULL END) AS COL9,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL8 ELSE NULL END) AS COL10,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL9 ELSE NULL END) AS COL11,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL10 ELSE NULL END) AS COL12,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL11 ELSE NULL END) AS COL13
FROM
(
------------------------------------------------------------------------------------------
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       AND D.CUIIO = 458868
      
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
       AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
  
  
---------------------------------------------------------------------  
) D 
LEFT JOIN
(

SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1) > 0  THEN 1 ELSE 0 END) AS CNT,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1) <= 2006   THEN 1 ELSE 0 END)   AS COL1,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2007   THEN 1 ELSE 0 END)   AS COL2,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2008   THEN 1 ELSE 0 END)   AS COL3,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2009   THEN 1 ELSE 0 END)   AS COL4,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2010   THEN 1 ELSE 0 END)   AS COL5,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2011   THEN 1 ELSE 0 END)   AS COL6,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2012   THEN 1 ELSE 0 END)   AS COL7,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2013   THEN 1 ELSE 0 END)   AS COL8,    
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2014   THEN 1 ELSE 0 END)   AS COL9,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2015   THEN 1 ELSE 0 END)   AS COL10,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2016   THEN 1 ELSE 0 END)   AS COL11    
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010)
    AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM

) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D

  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  D.ID_MDTABLE = 14612 

) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE,
--  T.ORDINE
  
UNION



SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CUATM,
  A.FULL_CODE,
  A.CUATM_DENUMIRE,
  A.DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) ORDINE,
--  A.RIND_D||'.'||A.RIND_S ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4,
  B.COL5,
  B.COL6,
  B.COL7,
  B.COL8,
  B.COL9,
  B.COL10,
  B.COL11,
  B.COL12,
  B.COL13
FROM
(
SELECT
      C.CODUL AS CUATM,
      C.FULL_CODE,
      C.DENUMIRE AS CUATM_DENUMIRE,
      B.RIND AS RIND_D,
      A.RIND AS RIND_S,
      B.ID_MD AS ID_MD_D,
      A.ID_MD AS ID_MD_S,
      B.CAPITOL,
      A.DENUMIRE,
      T.ORDINE
    FROM
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R 
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND IN ('1','2','3','4','5','6')
    ) A
    CROSS JOIN
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')

    ) B
    CROSS JOIN CIS2.VW_CL_CUATM C
    INNER JOIN
(
SELECT 
       D.ORDINE,
       D.RIND
       
       FROM CIS2.MD_RIND_OUT D
             
            WHERE 
   
      D.ID_MDTABLE = 14630



) T ON (T.RIND = B.RIND) 
    WHERE
      C.PRGS IN ('2') AND
      C.CODUL NOT IN ('9800000')
    ORDER BY
      T.ORDINE,
      B.RIND,
      A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CUATM,
  SUM(CASE WHEN D.CAPITOL IN (1010)  THEN D.COL1_S ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.CNT ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL2 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL3 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL4 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL5 ELSE NULL END) AS COL7,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL6 ELSE NULL END) AS COL8,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL7 ELSE NULL END) AS COL9,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL8 ELSE NULL END) AS COL10,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL9 ELSE NULL END) AS COL11,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL10 ELSE NULL END) AS COL12,
  SUM(CASE WHEN DD.CAPITOL IN (1010) THEN DD.COL11 ELSE NULL END) AS COL13
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  C.CODUL AS CUATM,
  --CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
   --   (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
         AND D.CUIIO = 458868 
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
    --  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
       AND D.CUIIO = 458868 
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  --INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
1=1
 -- CC.PRGS IN ('2')
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  C.CODUL,
  --CC.DENUMIRE,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  > 0  THEN 1 ELSE 0 END) AS CNT,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1) <= 2006   THEN 1 ELSE 0 END)   AS COL1,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2007   THEN 1 ELSE 0 END)   AS COL2,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2008   THEN 1 ELSE 0 END)   AS COL3,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2009   THEN 1 ELSE 0 END)   AS COL4,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2010   THEN 1 ELSE 0 END)   AS COL5,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2011   THEN 1 ELSE 0 END)   AS COL6,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2012   THEN 1 ELSE 0 END)   AS COL7,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2013   THEN 1 ELSE 0 END)   AS COL8,    
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2014   THEN 1 ELSE 0 END)   AS COL9,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2015   THEN 1 ELSE 0 END)   AS COL10,
   SUM(CASE WHEN D.RIND IN ('00') AND CIS2.NVAL(D.COL1)  = 2016   THEN 1 ELSE 0 END)   AS COL11    


FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010)
   AND D.CUIIO = 458868 
GROUP BY
  D.CUIIO,
  D.CUATM,
  D.CAPITOL
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CUATM=B.CUATM)
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL
-- ORDER BY
--  A.CUATM
  
--ORDER BY
--  FULL_CODE,
--  ORDINE
  
  
 
  
) VB
ORDER BY
  FULL_CODE,
  ORDINE
  

  
