
SELECT
   D.CUIIO,
   R.DENUMIRE,
   RD.RIND,
   RD.ORDINE,
   RD.DENUMIRE DENUMIRE_RIND,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)  THEN D.COL1 ELSE NULL END)) AS COL1,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)  THEN D.COL2 ELSE NULL END)) AS COL2,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)  THEN D.COL3 ELSE NULL END)) AS COL3

 
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
  INNER JOIN CIS2.MD_RIND RD ON (RD.ID_MD=D.ID_MD)
  

  
WHERE
  D.FORM IN (20)           AND 
  D.FORM_VERS = :PFORM_VERS   AND
 (D.PERIOADA IN(:pPERIOADA))   AND     
 (D.CAPITOL IN (1011)  AND D.RIND NOT IN ('-')) AND 
  
  D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%' 
AND D.CUIIO = 458868   

GROUP BY
   D.CUIIO,
   R.DENUMIRE,
   RD.RIND,
   RD.ORDINE,
   RD.DENUMIRE
 
    ORDER BY 
    D.CUIIO,
    RD.ORDINE   
    