INSERT INTO  --USER_BANCU.TABLE_OUT_TEST 
    
      CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
      COL1,
      COL2,
      COL3,
      COL4,
      COL5,
      COL6,
      COL7,
      COL8
    
    
      )

SELECT
  :PPERIOADA AS PERIOADA,
  :PFORM AS FORM,
  :PFORM_VERS AS FORM_VERS,
  :PID_MDTABLE AS ID_MDTABLE,
  :PCOD_CUATM AS COD_CUATM,
   R.CUIIO AS NR_SECTIE,
   R.CUIIO ||'-'||MAX(R.DENUMIRE) AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
 RD.RIND||'~'||RD.ORDINE||'~'||SUM(ROWNUM) AS NR_ROW,
   RD.ORDINE AS ORDINE,
   '00000000' AS DECIMAL_POS,
   RD.DENUMIRE  AS NUME_ROW, 
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)       THEN D.COL1 ELSE NULL END)) AS COL1,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA-1)     THEN D.COL1 ELSE NULL END)) AS COL2,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)       THEN D.COL2 ELSE NULL END)) AS COL3,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA-1)     THEN D.COL2 ELSE NULL END)) AS COL4,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA)       THEN D.COL3 ELSE NULL END)) AS COL5,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA-1)     THEN D.COL3 ELSE NULL END)) AS COL6,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA-1)     THEN D.COL3 ELSE NULL END)) AS COL7,
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1011) AND (D.PERIOADA=:PPERIOADA-1)     THEN D.COL3 ELSE NULL END)) AS COL8
 

   
   
   
   
   
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
  INNER JOIN CIS2.MD_RIND RD ON (RD.ID_MD=D.ID_MD)
  

  
WHERE
  D.FORM IN (20)           AND 
  D.FORM_VERS = :PFORM_VERS   AND
 (D.PERIOADA IN(:pPERIOADA,:pPERIOADA-1 ))   AND     
 (D.CAPITOL IN (1011)  AND D.RIND NOT IN ('-')) AND 
  
  D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%' 


GROUP BY
 RD.RIND,
 RD.DENUMIRE,
 RD.ORDINE,
 R.CUIIO
 
 
    ORDER BY 
    R.CUIIO   
    