--DECLARE
--
--  CURSOR C IS
--
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW  NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4,
--    DF.COL5
--   
--  
--
--   
--FROM 
--(
SELECT
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,   
  
  VB.FULL_CODE AS NR_SECTIE,                                                         
  VB.CFP_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
 CASE WHEN VB.COL2 = 0 THEN NULL ELSE VB.COL2 END||'~'||VB.ORDINE AS NR_ROW,

  VB.ORDINE,
  '0000' AS DECIMAL_POS,
  VB.DENUMIRE AS NUME_ROW,
   CASE WHEN VB.COL3 = 0 THEN NULL ELSE VB.COL3 END     AS COL1,
  CASE WHEN VB.COL4 = 0 THEN NULL ELSE VB.COL4 END     AS COL2,
  CASE WHEN VB.COL5 = 0 THEN NULL ELSE VB.COL5 END     AS COL3,
  CASE WHEN VB.COL6 = 0 THEN NULL ELSE VB.COL6 END     AS COL4,
  CASE WHEN VB.COL7 = 0 THEN NULL ELSE VB.COL7 END     AS COL5
FROM
(


SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CFP,
  T.FULL_CODE,
  T.CFP_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
 
    SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R301_1 ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R302_1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R303_1 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R304_1 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R305_1 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R305_2 ELSE NULL END) AS COL7

FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CFP,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
        AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
      (D.PERIOADA =:pPERIOADA) AND   
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
        AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)

  INNER JOIN CIS2.VW_CL_CFP C ON  (C.CODUL=A.CFP)
  INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  1=1
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CFP,
  D.CAPITOL,

    SUM(CASE WHEN D.RIND IN ('301') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R301_1,
  SUM(CASE WHEN D.RIND IN ('302') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R302_1,
  SUM(CASE WHEN D.RIND IN ('303') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R303_1,
  SUM(CASE WHEN D.RIND IN ('304') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R304_1,
  SUM(CASE WHEN D.RIND IN ('305') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R305_1,
  SUM(CASE WHEN D.RIND IN ('305') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R305_2
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1012)
  AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CFP
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CFP,
  C.FULL_CODE,
  C.DENUMIRE AS CFP_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D


  CROSS JOIN CIS2.VW_CL_CFP C
WHERE

   D.ID_MDTABLE = 14612 AND  C.CODUL NOT IN ('10','17','19','21','25','26','27','29') 
  

  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CFP=D.CFP)

GROUP BY
  T.CFP,
  T.FULL_CODE,
  T.CFP_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE,
--  T.ORDINE

    UNION 

SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CFP,
  A.FULL_CODE,
  A.CFP_DENUMIRE,
  A.DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) ORDINE,
--  A.RIND_D||'.'||A.RIND_S ORDINE,
--  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4,
  B.COL5,
  B.COL6,
  B.COL7

FROM
(
SELECT
      C.CODUL AS CFP,
      C.FULL_CODE,
      C.DENUMIRE AS CFP_DENUMIRE,
      B.RIND AS RIND_D,
      A.RIND AS RIND_S,
      B.ID_MD AS ID_MD_D,
      A.ID_MD AS ID_MD_S,
      B.CAPITOL,
      A.DENUMIRE,
      T.ORDINE
    FROM
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R 
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND IN ('1','2','3','4','5','6')
    ) A
    CROSS JOIN
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')

    ) B
    CROSS JOIN CIS2.VW_CL_CFP C
    INNER JOIN
(
SELECT 
       D.ORDINE,
       D.RIND
       
       FROM CIS2.MD_RIND_OUT D
             
            WHERE 
   
      D.ID_MDTABLE = 14630



) T ON (T.RIND = B.RIND) 
    WHERE
    1=1
--      C.PRGS IN ('2') AND
--      C.CODUL NOT IN ('9800000')
    ORDER BY
      T.ORDINE,
      B.RIND,
      A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CFP,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R301_1 ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R302_1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R303_1 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R304_1 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R305_1 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1012) THEN DD.R305_2 ELSE NULL END) AS COL7
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  C.CODUL AS CFP,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    
    WHERE
      (D.PERIOADA =:pPERIOADA) AND   
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
        AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
    
     (D.PERIOADA =:pPERIOADA) AND   
    (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
        AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
INNER JOIN CIS2.VW_CL_CFP C ON (A.CFP=C.CODUL)
--INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  C.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CFP,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('301') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R301_1,
  SUM(CASE WHEN D.RIND IN ('302') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R302_1,
  SUM(CASE WHEN D.RIND IN ('303') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R303_1,
  SUM(CASE WHEN D.RIND IN ('304') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R304_1,
  SUM(CASE WHEN D.RIND IN ('305') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R305_1,
  SUM(CASE WHEN D.RIND IN ('305') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R305_2
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1012)
    AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
  D.CFP,
  D.CAPITOL
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CFP C ON (D.CFP=C.CODUL)
  INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
1=1
--  CC.PRGS IN (2) AND
--  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CFP=B.CFP)
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL
-- ORDER BY
--  A.FULL_CODE
--WHERE
--  A.CFP=B.CFP OR
--  B.CFP IS NULL
--ORDER BY
-- A.CUATM


) VB
ORDER BY
  VB.FULL_CODE,
  VB.ORDINE
  
--   )  DF;
--  
--  
--  BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--    INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
--    
--     CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4, COL5
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5
--    );
--  END LOOP;
--END;