SELECT DISTINCT
'Rînd 700: ' || 
  
  NVAL(SUM(CASE WHEN D.RIND IN('700') THEN CIS2.NVAL(D.COL1)  ELSE NULL END)) ||' >  '|| '1800 sau = 0 ' 
   
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (20) 
HAVING


NVAL((SUM(CASE WHEN D.CAPITOL IN (3) AND D.RIND IN('01') THEN CIS2.NVAL(D.COL1)  ELSE NULL END))) = 1

AND 

(
   NVAL((SUM(CASE WHEN D.CAPITOL IN (1016) AND D.RIND IN('700') THEN CIS2.NVAL(D.COL1)  ELSE NULL END))) = 0
   
   OR  
   NVAL((SUM(CASE WHEN D.CAPITOL IN (1016) AND D.RIND IN('700') THEN CIS2.NVAL(D.COL1)  ELSE NULL END))) > 1800
   
   )    
   
   
   
