SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
  SUM(CASE WHEN D.CAPITOL IN (1010) THEN D.COL1_S ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_1 ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R202_1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R203_1 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R204_1 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R205_1 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_3 ELSE NULL END) AS COL7,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R206_1 ELSE NULL END) AS COL8,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R207_1 ELSE NULL END) AS COL9
FROM
(
------------------------------------------------------------------------------------------
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D

    WHERE
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      (D.PERIOADA =:pPERIOADA) AND  
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
  
  
---------------------------------------------------------------------  
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('201') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R201_1,
  SUM(CASE WHEN D.RIND IN ('201') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R201_2,
  SUM(CASE WHEN D.RIND IN ('201') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R201_3,
  SUM(CASE WHEN D.RIND IN ('202') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R202_1,
  SUM(CASE WHEN D.RIND IN ('202') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R202_2,
  SUM(CASE WHEN D.RIND IN ('202') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R202_3,
  SUM(CASE WHEN D.RIND IN ('203') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R203_1,
  SUM(CASE WHEN D.RIND IN ('203') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R203_2,
  SUM(CASE WHEN D.RIND IN ('203') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R203_3,
  SUM(CASE WHEN D.RIND IN ('204') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R204_1,
  SUM(CASE WHEN D.RIND IN ('204') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R204_2,
  SUM(CASE WHEN D.RIND IN ('204') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R204_3,
  SUM(CASE WHEN D.RIND IN ('205') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R205_1,
  SUM(CASE WHEN D.RIND IN ('205') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R205_2,
  SUM(CASE WHEN D.RIND IN ('205') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R205_3,
  SUM(CASE WHEN D.RIND IN ('206') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R206_1,
  SUM(CASE WHEN D.RIND IN ('206') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R206_2,
  SUM(CASE WHEN D.RIND IN ('206') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R206_3,
  SUM(CASE WHEN D.RIND IN ('207') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R207_1,
  SUM(CASE WHEN D.RIND IN ('207') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R207_2,
  SUM(CASE WHEN D.RIND IN ('207') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R207_3
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1011)
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D
--(
--SELECT 'TOTAL' AS DENUMIRE,                                      '100'   AS ORDINE, '101-102-103-104-105-106-107-108-109-110-111-112-113.1-113.2-113.3-113.4-113.5' AS RIND FROM DUAL UNION
--SELECT 'Hoteluri si moteluri' AS DENUMIRE,                       '100.1' AS ORDINE, '101-102-103'  AS RIND FROM DUAL UNION
--SELECT 'Hoteluri' AS DENUMIRE,                                   '101'   AS ORDINE, '101' AS RIND FROM DUAL UNION
--SELECT 'Hoteluri de tip apartament' AS DENUMIRE,                 '102'   AS ORDINE, '102' AS RIND FROM DUAL UNION
--SELECT 'Moteluri' AS DENUMIRE,                                   '103'   AS ORDINE, '103' AS RIND FROM DUAL UNION
--SELECT 'Camine pentru vizitatori' AS DENUMIRE,                   '104' AS ORDINE,   '113.4' AS RIND FROM DUAL UNION
--SELECT 'Pensiuni turistice si agroturistice - total' AS DENUMIRE,'105' AS ORDINE,   '106-107' AS RIND FROM DUAL UNION  
--SELECT 'Pensiuni turistice.' AS DENUMIRE,                        '106'   AS ORDINE, '106' AS RIND FROM DUAL UNION  
--SELECT 'Pensiuni agroturistice.' AS DENUMIRE,                    '107'   AS ORDINE, '107' AS RIND FROM DUAL UNION  
--
--SELECT 'Structuri de intremare' AS DENUMIRE,                     '108'   AS ORDINE, '113.1-113.2-113.3' AS RIND FROM DUAL UNION 
--SELECT 'Sanatorii'              AS DENUMIRE,                     '109' AS ORDINE,   '113.1'  AS RIND FROM DUAL UNION 
--SELECT 'Pensiuni  de tratament' AS DENUMIRE,                     '110' AS ORDINE,   '113.2'  AS RIND FROM DUAL UNION 
--SELECT 'Alte structiri de intremare' AS DENUMIRE,                '111' AS ORDINE,   '113.3'  AS RIND FROM DUAL UNION
--SELECT 'Structuri de odihna' AS DENUMIRE,                        '112'   AS ORDINE, '104-105-108-109' AS RIND FROM DUAL UNION
--SELECT 'Vila turistica'      AS DENUMIRE,                        '113' AS ORDINE,   '104'    AS RIND FROM DUAL UNION
--SELECT 'Bungalou'            AS DENUMIRE,                        '114'   AS ORDINE, '105'    AS RIND FROM DUAL UNION
--SELECT 'Sate de vacanta si alte structuri' AS DENUMIRE,          '115' AS ORDINE,   '109'  AS RIND FROM DUAL UNION
--SELECT 'Camping'                           AS DENUMIRE,          '116' AS ORDINE,   '108'    AS RIND FROM DUAL UNION
--SELECT 'Tabere de vacanta'                 AS DENUMIRE,          '117' AS ORDINE,   '110'    AS RIND FROM DUAL 
--ORDER BY ORDINE
--) D
  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  D.ID_MDTABLE = 7389 

) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE