SELECT

  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,

  SUM(DD.CNT) AS COL1,
  SUM(DD.R201_2) AS COL2,
  SUM(DD.R202_2) AS COL3,
  SUM(DD.R203_2) AS COL4,
  SUM(DD.R204_2) AS COL5,
  SUM(DD.R205_2) AS COL6,
  SUM(DD.R516_1) AS COL7

FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
         AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
      (D.PERIOADA =:pPERIOADA) AND   
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
         AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  --D.CAPITOL,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') AND CIS2.NVAL(D.COL2) > 0 THEN 1 END) AS CNT,  
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R201_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R201_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R201_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R202_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R202_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R202_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R203_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R203_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R203_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R204_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R204_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R204_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R205_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R205_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R205_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R206_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R206_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R206_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R207_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R207_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R207_3,
  
  SUM(CASE WHEN D.CAPITOL IN (1016) AND D.RIND IN ('516') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R516_1
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1011,1016)
   AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
 -- D.CAPITOL,
  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D


  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  D.ID_MDTABLE = 14612 
  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
ORDER BY
  T.FULL_CODE,
   T.ORDINE